#!/bin/bash
APP_NAME=$1
NEO=./target/sdk/tools/neo.sh
pwd
echo Deploying "$.travis.yml"
$NEO deploy -a "$jaehyunseo" \
       -b "$APP_NAME" \
       -h "$hanatrial.ondemand.com" \
       -u "$jaehyunseo" \
       -p "$Wogus339#" \
       -s ./target/basecamp-1.0.0.war
echo Restarting app...
$NEO restart -a "$ACCOUNT" \
             -b "$APP_NAME" \
             -h "$hanatrial.ondemand.com" \
             -u "$jaehyunseo" \
             -p "$Wogus339#"
echo DEPLOYMENT FINISHED
